name: SonarQube (Backend only, no tests)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read
  pull-requests: read

env:
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
  SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      # Build ONLY to generate compiled classes; skip all tests
      - name: Build (skip tests)
        run: ./mvnw -B -U clean package -DskipTests -DskipITs=true

      # Run SonarQube scan (no coverage)
      - name: SonarQube Scan
        run: |
          ./mvnw -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url="${SONAR_HOST_URL}" \
            -Dsonar.login="${SONAR_TOKEN}" \
            -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
            -Dsonar.projectName="ERP Backend" \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.exclusions=**/target/**,**/node_modules/**,**/*.md,**/*.yml,**/*.yaml,**/*.json
